### ISSUE TITLE
What about delegates?

### ISSUE THREAD

**Issue by SeRG1k17** [markspanbroek/MockingInSwift#2]
```swift
class CBCentralManagerMock: CBCentralManagerType {

var delegate: CBCentralManagerDelegate?

func scanForPeripherals(withServices serviceUUIDs: [CBUUIDType]?, options: [String : Any]?) {

let perepheral = CBPeripheralMock()

let data: [String: Any] = [CBAdvertisementDataLocalNameKey: "nameHere"]

//delegate?.centralManager(self, didDiscover: perepheral, advertisementData: data, rssi: 0)
}
//...
}
```
Apply the same approach as with classes, it does not work out here:
```swift
extension CBCentralManagerDelegate: CBCentralManagerDelegateType {}
```

**Comment by markspanbroek** [comment]
Hi @SeRG1k17, my apologies for the late reply. Could you elaborate on what you're trying to accomplish, if you'd still like some help with this issue? From the code above I'm not quite sure whether you'd like to mock the CBCentralManager or its delegate.

If you'd like to mock the manager, then it's not necessary to introduce a CBCentralManagerDelegateType, because you can just use a regular CBCentralManagerDelegate. If you'd like to mock the delegate, then it's also not necessary to introduce a CBCentralManagerType, because you could just create a CBCentralManagerDelegate that checks your test condition.
